package com.fanhl.kona.kona.entity

data class KonaPost(
    val id: Int? = null,
    val tags: String? = null,
    val createdAt: Long? = null,
    val creatorId: Int? = null,
    val author: String? = null,
    val change: Int? = null,
    val source: String? = null,
    val score: Int? = null,
    val md5: String? = null,
    val fileSize: Int? = null,
    val fileUrl: String? = null,
    val isShownInIndex: Boolean? = null,
    val previewUrl: String? = null,
    val previewWidth: Int? = null,
    val previewHeight: Int? = null,
    val actualPreviewWidth: Int? = null,
    val actualPreviewHeight: Int? = null,
    val sampleUrl: String? = null,
    val sampleWidth: Int? = null,
    val sampleHeight: Int? = null,
    val sampleFileSize: Int? = null,
    val jpegUrl: String? = null,
    val jpegWidth: Int? = null,
    val jpegHeight: Int? = null,
    val jpegFileSize: Int? = null,
    val rating: String? = null,
    val hasChildren: Boolean? = null,
    val parentId: Int? = null,
    val status: String? = null,
    val width: Int? = null,
    val height: Int? = null,
    val isHeld: Boolean? = null,
    val framesPendingString: String? = null,
    val framesPending: List<String>? = null,
    val framesString: String? = null,
    val frames: List<String>? = null,
)
